include:
  - project: devops/ci-config
    ref: main
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml
      - /templates/downstream-submodule-workflow.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 3

stages:
  - pre-build
  - build
  - test

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

pre-build:
  stage: pre-build
  extends: .update_pipeline_submodules

build:
  extends: .build

test:
  extends: .test
  artifacts:
    paths:
      - selenium/screenshots
    expire_in: 1 week
