# todo: simplify or load minimum test info needed from local files 
# for teardown and startup and to remove volumes

services:

  httpd:
    build: apache
    links:
    - "tomcat-pn"
    - "xsugar"
    - "fuseki"
    - "solr"
    - "sosol"
    volumes:
    - repo:/srv
    ports:
    - "8000:80"
    depends_on:
    - xsugar
    - tomcat-pn
    - solr
    - fuseki
    - sosol
  sosol:
    build: sosol
    ports:
    - "8080:8080"
    volumes:
    - repo:/srv
    - ./sosol-compose:/opt/sosol-compose
    command: /opt/sosol-compose/migrate-and-copy.sh
    links:
    - "xsugar"
    - "postgres"
    depends_on:
    - postgres
    - repo_clone
    - xsugar
  repo_clone:
    build: repo_clone
  xsugar:
    build: xsugar
  navigator:
    build: navigator-compose
    depends_on:
    - repo_clone
    - fuseki
    links:
    - "fuseki"
  fuseki:
    # built from https://github.com/dcthree/docker-fuseki
    image: ryanfb/fuseki
    volumes:
    - repo:/srv
    - fuseki_data:/data
    cpu_count: 2
    environment:
    - OPTS=--port=8090 --tdb2 --loc=/data --update /pi
    - JVM_ARGS=-Xmx8192M
    - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    ports:
    - "8090:8090"
  postgres:
    image: postgres:13
    environment:
    - POSTGRES_USER=papyri
    - POSTGRES_HOST_AUTH_METHOD=trust
  solr:
    build: solr
    ports:
    - "8983:8983"
    volumes:
    - solr_data:/opt/solr/server/solr
    environment:
    - SOLR_JAVA_MEM=-Xms1G -Xmx8G
    depends_on:
    - navigator
  tomcat-pn:
    build: tomcat-pn
    links:
    - "postgres"
    - "fuseki"
    volumes:
    - repo:/srv
    depends_on:
    - navigator
    
    
  ruby_acceptance_tests:
    build: selenium-ruby
    depends_on:
    - selenium
    - httpd
    ports:
    - "1111:1111"
    links:
    - "selenium"
    - "httpd"
    environment:
    - SELENIUM_HOST=selenium
    - SELENIUM_PORT=4444
    profiles:
      - test

  selenium:
    image: selenium/standalone-chromium:latest
    links: 
      - "httpd"
    # # Test to see if the service is healthy
    # healthcheck: 
    #   test: ["CMD", "curl", "-f", "http://httpd:80/"]
    #   interval: 20s
    #   timeout: 15s
    #   retries: 5
    ports:
    - "4444:4444"
    - "7900:7900"
    shm_size: 2g
    profiles:
      - test

networks:
  selenium-net:
    driver: bridge

volumes:
  repo:
  fuseki_data:
  solr_data: